services:
  - type: web
    name: iiap-investigaciones-web
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true

    envVars:
      - key: NODE_ENV
        value: production
